# Generated by Django 5.2 on 2025-05-19 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.CharField(max_length=10000)),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
